services:
  service:
    build: ./service/
    ports:
      - 8000:8000
    volumes:
      - ./service/:/srv/
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=admin
      - DB_URL=http://db:3030
      - DB_DATASET=${DB_DATASET}
    
  app:
    build: ./webui/
    ports:
      - 8001:3000
    volumes:
      - ./webui/src/:/srv/src/
    environment:
      - VITE_DB_PASSWORD=${DB_PASSWORD}
      - VITE_DB_USER=admin
      - VITE_DB_URL=${DB_URL}
      - VITE_DB_DATASET=${DB_DATASET}
      - VITE_SERVICE_URL=${SERVICE_URL}
    
  db:
    image: stain/jena-fuseki
    ports:
      - 3030:3030
    volumes:
      - ./db_storage:/fuseki
    environment:
      - ADMIN_PASSWORD=${DB_PASSWORD}
      - TDB=2